spring.application.name=cryptopal
spring.docker.compose.file=../../../compose.yaml
server.port=8080
#database information
spring.datasource.url=jdbc:postgresql://localhost:5432/cryptopal
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}

#hibernate does not create tables automatically only flyway does, it validates the schema
spring.jpa.hibernate.ddl-auto=validate
spring.data.redis.host=localhost
spring.data.redis.port=6379

#gemini info
gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-3.6-flash